name: Image Conversion

on:
  push:
  workflow_dispatch:

jobs:
  imgconv:
    runs-on: ubuntu-latest

    env:
      DRAWIO_VER: 21.5.1

    steps:
      - uses: actions/checkout@v3

      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: '1.6.14'

      - name: Install dependencies
        run: |
          wget -q -Odrawio.deb https://github.com/jgraph/drawio-desktop/releases/download/v${DRAWIO_VER}/drawio-amd64-${DRAWIO_VER}.deb
          sudo apt-get update && apt-get upgrade -y && apt install ./drawio.deb
          rm drawio.deb
      
      - name: Compile converter
        run: cd .ci && nim c -o:../conv -d:danger converter.nim && cd ..
